# Introduction to python

In [1]:
print("Hello World !")

Hello World !


### variables and types

In [2]:
x = 12

In [3]:
type(x)

int

In [4]:
x = 12.5
type(x)

float

In [5]:
s = 'Python'

In [6]:
type(s)

str

In [7]:
s
print(s)

Python


### Arithmetic operation

In [8]:
a = 2
b = 3.5
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a // b)

5.5
-1.5
7.0
0.5714285714285714
2.0
0.0


### conditions

In [9]:
if a > b:
    print('a is greater than b')
    print(a)
elif not(a == b) and a < b:
        print('b is greater than a')
        print(b)   
else:
    print('a and b are equal')

b is greater than a
3.5


### take input from user

In [10]:
name = input("What is your name ..")
print("your name is ", name)

What is your name ..Salma Alhagry
your name is  Salma Alhagry


### loops

In [11]:
i = 10
while i > 0:
    print(i)
    i = i - 1

10
9
8
7
6
5
4
3
2
1


In [12]:
i = 10
while True:
    if i == 0:
        break
    print(i)
    i = i - 1

10
9
8
7
6
5
4
3
2
1


In [13]:
for x in range(5,10):
    print(x)

5
6
7
8
9


### functions

In [14]:
def add2num(x, y):
    return x,y

In [15]:
a, b = add2num(2,3)

This is Python

In [16]:
#comment
print(a)
print(b)

2
3


In [17]:
def fact(n):
    if not isinstance(n, int):
        print("Error: floating number!")
        return None
    if n < 0:
        print("Error: negative number !")
        return None
    elif n == 0:
        return 1
    else:
        return n * fact(n-1)

In [18]:
fact(2.5)

Error: floating number!


### list

In [19]:
l = []
type(l)

list

In [20]:
l.append(1)

In [21]:
l

[1]

In [22]:
len(l)

1

In [23]:
l[0]

1

In [24]:
l = l + [2.5]

In [25]:
l

[1, 2.5]

In [26]:
l1 = ['abc', 23, 3.4, [1, 3, 5]]

In [27]:
len(l)

2

In [28]:
l[0]

1

In [29]:
l[1]

2.5

In [30]:
len(l1)

4

In [31]:
len(l1[3])

3

In [32]:
l1[-1]

[1, 3, 5]

In [33]:
l1[-2]

3.4

In [34]:
l1

['abc', 23, 3.4, [1, 3, 5]]

In [35]:
l1[2:4]

[3.4, [1, 3, 5]]

In [36]:
l2 = [0,1,2,3,4,5,6,7,8,9]

In [37]:
l2[2:6]

[2, 3, 4, 5]

In [38]:
l2[2:]

[2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
l2[:4]

[0, 1, 2, 3]

In [40]:
ll2 = l2[2:]

In [41]:
ll2

[2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
s

'Python'

In [43]:
s[0]

'P'

In [44]:
min(l2)

0

In [45]:
max(l2)

9

In [46]:
l3 = [3,2,67,11,34,5,76]

In [47]:
l3

[3, 2, 67, 11, 34, 5, 76]

In [48]:
l3.sort()

In [49]:
l3

[2, 3, 5, 11, 34, 67, 76]

In [50]:
l3[1:-1]

[3, 5, 11, 34, 67]

In [51]:
l3[1:-2]

[3, 5, 11, 34]

### numpy

In [52]:
import numpy as np

In [53]:
v = np.array([1,2,3])

In [54]:
np.sum(v)

6

In [55]:
m = np.array([[1,2,3],[4,5,6]])

In [56]:
v.shape

(3,)

In [57]:
m.shape

(2, 3)

In [58]:
x = m.reshape(1,6)

In [59]:
m.shape

(2, 3)

In [60]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
x.shape

(1, 6)

In [62]:
x

array([[1, 2, 3, 4, 5, 6]])

In [63]:
mm = np.matrix([[1,2,3],[4,5,6]])

In [64]:
mm.shape

(2, 3)

In [65]:
mt = m.T

In [66]:
m.shape

(2, 3)

In [67]:
mt.shape

(3, 2)

In [68]:
z = np.zeros(4)

In [69]:
z

array([0., 0., 0., 0.])

In [70]:
z.shape

(4,)

In [71]:
zz = np.zeros((2,3))

In [72]:
zz.shape

(2, 3)

In [73]:
zz

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
o = np.ones((2,3))

In [75]:
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
e = np.eye(5)

In [77]:
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
r = np.random.random((3,4))

In [79]:
r

array([[0.64994768, 0.02239217, 0.70225596, 0.724097  ],
       [0.73188691, 0.01905067, 0.1243943 , 0.71409513],
       [0.26184426, 0.29958316, 0.87988104, 0.62797214]])

In [80]:
rr = np.random.randn(3,4)

In [81]:
rr

array([[-0.57873033,  0.9551167 , -0.73172956,  1.1707962 ],
       [ 0.93063038,  0.432875  ,  1.79652083, -0.39695141],
       [ 0.71065274,  0.15946512, -0.0985735 ,  1.04230765]])

In [82]:
rri = np.random.randint(10, size=(2,3))

In [83]:
rri

array([[4, 9, 9],
       [7, 3, 1]])

In [84]:
r + rr

array([[ 0.07121736,  0.97750886, -0.0294736 ,  1.8948932 ],
       [ 1.66251729,  0.45192566,  1.92091513,  0.31714371],
       [ 0.972497  ,  0.45904828,  0.78130754,  1.67027979]])

In [85]:
rt = rr.T

In [86]:
r.shape

(3, 4)

In [87]:
rt.shape

(4, 3)

In [88]:
rt.dot(r)

array([[ 0.4910521 ,  0.2176697 ,  0.33463816,  0.69177185],
       [ 0.97934646,  0.07740675,  0.86489391,  1.10085071],
       [ 0.81345324, -0.01169105, -0.37711744,  0.69114219],
       [ 0.74335501,  0.33091229,  1.68992686,  1.21884911]])

In [89]:
np.trace(r)

1.5488793953597761

In [90]:
r.mean()

0.4797833675938354

In [91]:
r.var()

0.08886563733522046